AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - '**/spec/**/*.rb'
Rails:
  Enabled: true

AbcSize:
  Max: 30

DotPosition:
  EnforcedStyle: trailing

ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 250
  IgnoredPatterns: ['^\s*#']

MethodLength:
  Max: 20

Rails/SkipsModelValidations:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BlockComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false
